[platformio]
default_envs = esp32

[env]
framework = arduino
monitor_speed = 115200
build_flags =
  -D CORE_DEBUG_LEVEL=0

[env:esp32]
platform = espressif32
board = esp32dev
lib_deps =
  marvinroger/AsyncMqttClient@^0.9.0
  AsyncTCP@^1.1.1

[env:esp8266]
platform = espressif8266
board = nodemcuv2
lib_deps =
  marvinroger/AsyncMqttClient@^0.9.0
  ESPAsyncTCP@^1.2.2

[env:mega]
platform = atmelavr
board = megaatmega2560
lib_deps =
  knolleary/PubSubClient@^2.8

[env:uno]
platform = atmelavr
board = uno
lib_deps =
  knolleary/PubSubClient@^2.8

[env:nano]
platform = atmelavr
board = nanoatmega328
lib_deps =
  knolleary/PubSubClient@^2.8
